### ISSUE TITLE
client and server on same machine

### ISSUE THREAD

**Issue by darktim** [lelutin/puppet-apt_cacher_ng#4]
Hi

I want to use the client and the server class on the same machine. At a first glance this sound silly, but it makes sense under certain prerequisites.

1. all servers are behind a loadbalancer
2. all clients configs are in a base class (which is also inherited by the apt-cache-ng servers)

Unfortunately I am getting this error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Anchor[begin] is already declared in file /etc/puppet/environments/production/modules/apt_cacher_ng/manifests/client.pp:21; cannot redeclare at /etc/puppet/environments/production/modules/apt_cacher_ng/manifests/init.pp:18 on node debianpackages-vm-inx01.intra.local.ch
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

I think the easiest and least intrusive thing would be to rename the anchor of the client calss so it does not collide with the server/init class:

  anchor { 'begin_client': } ->
  class { 'apt_cacher_ng::client::config': } ->
  anchor { 'end_client': }

 What do you think?

Greetz,
Andre

**Comment by lelutin** [comment]
ah! indeed, good catch!

What I did in another module was to use the class name followed by ::begin and ::end to avoid any chance of clashes with other modules also declaring anchors.
See: https://github.com/lelutin/puppet-fail2ban/blob/master/manifests/init.pp

I'll merge in your change, but rename the anchors to "apt_cacher_ng::begin" and apt_cacher_ng::client::begin" (same for ::end), and retain full credit to you.

**Comment by lelutin** [comment]
corrected the anchor names as I said and also the commit message to make it more useful.

I've pushed 3156316f4f44f8f63f58631c56691fead589e00d which resolves this issue.

Thanks a bunch for this!
